name: flutter_parking_management
packages:
  - "apps/**"
  - "packages/**"

command:
  bootstrap:
    usePubspecOverrides: true
    runPubGetInParallel: false
  clean:
    hooks:
      post: melos exec --flutter --concurrency=1 -- "flutter clean"
