name: common_deps
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.5
  flutter_modular: ^6.3.2
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.2.0
  nil: ^1.1.1
  rxdart: ^0.27.7
  collection: ^1.18.0
  dartz: ^0.10.1
  shimmer: ^3.0.0
  mocktail: ^1.0.3
  faker: ^2.1.0
  uuid: ^4.4.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
